name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-node-world:$(date +%s)
      
    - name: Download Sysdig CLI
      run: |
        curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/darwin/amd64/sysdig-cli-scanner"
        chmod +x ./sysdig-cli-scanner
    
    - name: Scan Image
      run: SECURE_API_TOKEN=7d9fd1d2-e2b2-4d23-8d29-dfbe44b0663e ./sysdig-cli-scanner --apiurl https://us2.app.sysdig.com test
